const {test,before,after}=require('node:test');const assert=require('node:assert/strict');
const enabled=process.env.FIRESTORE_EMULATOR_HOST==='127.0.0.1:8188'&&process.env.GCLOUD_PROJECT==='demo-wearquest';
let db,server,base,superCookie,viewerCookie,opsCookie,superId,viewerId;
const C=require('../core');const origin='https://wearquest-admin-9a45f.web.app';
async function request(path,{method='GET',body,cookie=superCookie,csrf='test-csrf',originValue=origin,key}={}){const response=await fetch(base+'/api/admin/'+path,{method,headers:{Origin:originValue,...(cookie?{Cookie:'__session='+cookie}:{}),...(method!=='GET'?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{}),...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await response.json()}catch{data={}}return {status:response.status,data,response};}
before(async()=>{if(!enabled)return;const {app}=require('../index');const {getFirestore,Timestamp}=require('firebase-admin/firestore');db=getFirestore();server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base='http://127.0.0.1:'+server.address().port;for(const role of ['superadmin','viewer','operations']){const id='test-'+role,token=C.random();await db.doc('admins/'+id).set({username:role,displayName:role,role,status:'active',authVersion:1,createdAt:Timestamp.now()});await db.doc('sessions/'+C.hash(token)).set({scope:'admin',adminId:id,authVersion:1,csrf:'test-csrf',expiresAt:Timestamp.fromMillis(Date.now()+3600000)});if(role==='superadmin'){superCookie=token;superId=id;}if(role==='viewer'){viewerCookie=token;viewerId=id;}if(role==='operations')opsCookie=token;}await db.doc('users/test-member').set({displayName:'Test',createdAt:Timestamp.now()});await db.doc('wallets/test-member').set({balance:30});});
after(async()=>{if(server)await new Promise(r=>server.close(r));});
test('unauthenticated, regular user, role, origin and CSRF boundaries',{skip:!enabled},async()=>{assert.equal((await request('dashboard',{cookie:''})).status,401);assert.equal((await request('dashboard',{cookie:'ordinary-user-token'})).status,401);assert.equal((await request('settings',{cookie:viewerCookie})).status,403);assert.equal((await request('settings',{originValue:'https://evil.example'})).status,403);assert.equal((await request('points/adjust',{method:'POST',body:{uid:'test-member',delta:1,reason:'test'},csrf:'wrong'})).status,403);assert.equal((await request('points/adjust',{cookie:opsCookie,method:'POST',body:{uid:'test-member',delta:1,reason:'test'}})).status,403);});
test('simultaneous duplicate point adjustments are exactly once and audited',{skip:!enabled},async()=>{const key=crypto.randomUUID(),body={uid:'test-member',delta:5,reason:'emulator only'};const results=await Promise.all([request('points/adjust',{method:'POST',body,key}),request('points/adjust',{method:'POST',body,key})]);assert.deepEqual(results.map(x=>x.status),[200,200]);assert.equal((await db.doc('wallets/test-member').get()).data().balance,35);assert.equal((await db.collection('pointTransactions').where('uid','==','test-member').get()).size,1);assert.equal((await db.collection('adminAudit').where('action','==','points.adjust').get()).size,1);assert.equal((await request('points/adjust',{method:'POST',body:{...body,delta:6},key})).status,409);assert.equal((await request('points/adjust',{method:'POST',body:{...body,delta:-100},key:crypto.randomUUID()})).status,400);});
test('order cancellation refunds once and restores stock; invalid transitions reject',{skip:!enabled},async()=>{const {Timestamp}=require('firebase-admin/firestore');await db.doc('products/test-product').set({name:'test',options:[{id:'o1',stock:4}],createdAt:Timestamp.now()});await db.doc('orders/test-order').set({uid:'test-member',status:'received',totalPoints:30,items:[{productId:'test-product',optionId:'o1',quantity:1}],shipping:{address:'private address'},createdAt:Timestamp.now()});const key=crypto.randomUUID(),body={status:'cancelled',reason:'test'};const results=await Promise.all([request('orders/test-order/status',{method:'POST',body,key}),request('orders/test-order/status',{method:'POST',body,key})]);assert.deepEqual(results.map(x=>x.status),[200,200]);assert.equal((await db.doc('products/test-product').get()).data().options[0].stock,5);assert.equal((await db.doc('wallets/test-member').get()).data().balance,65);assert.equal((await request('orders/test-order/status',{method:'POST',body,key:crypto.randomUUID()})).status,409);const listing=await request('list/orders');assert.equal(listing.status,200);assert.equal('shipping'in listing.data.items[0],false);assert.equal((await request('detail/orders/test-order',{cookie:viewerCookie})).status,403);});
test('published policies are immutable and version uniqueness enforced',{skip:!enabled},async()=>{const body={kind:'terms',title:'Test',body:'Not real terms',version:'test-v1',effectiveDate:'2026-09-29',status:'published',summary:'test only',reviewed:true};assert.equal((await request('policies/test-policy',{method:'POST',body})).status,200);assert.equal((await request('policies/test-policy',{method:'POST',body:{...body,body:'overwrite'}})).status,409);assert.equal((await request('policies/duplicate-version',{method:'POST',body})).status,409);assert.equal((await request('policies/unreviewed',{method:'POST',body:{...body,version:'v2',reviewed:false}})).status,400);});
test('unimplemented providers cannot be marked active; no self privilege changes',{skip:!enabled},async()=>{assert.equal((await request('providers/kakao',{method:'POST',body:{label:'Kakao',order:1,enabled:true,clientId:''}})).status,409);assert.equal((await request('admins/'+superId,{method:'POST',body:{role:'viewer',status:'active',reason:'test'}})).status,403);});
test('session revocation applies immediately',{skip:!enabled},async()=>{await db.doc('admins/'+viewerId).update({authVersion:2});assert.equal((await request('list/products',{cookie:viewerCookie})).status,403);});
test('spoofed image bytes and path traversal are rejected',{skip:!enabled},async()=>{const r=await fetch(base+'/api/admin/images',{method:'POST',headers:{Origin:origin,Cookie:'__session='+superCookie,'X-CSRF-Token':'test-csrf','Content-Type':'image/png'},body:Buffer.from('<script>alert(1)</script>')});assert.equal(r.status,400);assert.equal((await request('images/invalid%2Fpath',{method:'DELETE'})).status,400);});
