'use strict';
const gameStatus={started:'미완료 (진행·이탈)',completed:'클리어',abandoned:'중단'};
async function gameManagement(v,q){
 const query=new URLSearchParams(q);if(!query.get('day'))query.set('day',today());
 const [data,plays]=await Promise.all([api('games?day='+encodeURIComponent(query.get('day'))),api('game-plays?'+query)]);
 if(v!==renderVersion)return;
 const t=data.total,unfinished=Math.max(0,t.started-t.completed-t.abandoned);
 const cards=[['참여 회원',t.participants+'명'],['플레이 시작',t.started+'회'],['클리어',t.completed+'회'],['중단',t.abandoned+'회'],['미완료',unfinished+'회'],['평균 클리어 시간',t.completed?Math.round(t.durationMs/t.completed/1000)+'초':'—']];
 const filters=`<form class="filters" id="gameFilterForm"><div class="field"><label>시작 날짜 (한국 시간)</label><input name="day" type="date" required value="${esc(data.day)}"></div><div class="field"><label>게임 (이력 필터)</label><select name="gameId"><option value="">전체</option>${data.items.map(g=>`<option value="${g.id}" ${query.get('gameId')===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select></div><div class="field"><label>회원번호 (이력 필터)</label><input name="uid" maxlength="128" value="${esc(query.get('uid')||'')}" placeholder="회원번호 정확히 입력"></div><button class="dark">조회</button></form>`;
 $('#content').innerHTML=head('게임 관리','게임 운영 상태와 로그인 회원의 플레이 기록을 관리합니다.')+`<div class="notice">통계는 선택한 날짜에 시작한 플레이 기준입니다. 회원 수는 중복을 제외합니다. 미완료에는 진행 중·브라우저 종료가 포함됩니다. 클리어는 게임에서 전송한 결과이며, 포인트 지급 검증 및 서버 포인트 적립과는 별도입니다.</div><div class="table-card">${filters}</div><div class="section-label"><h2>${esc(data.day)} · 전체 게임 통계</h2></div><div class="cards">${cards.map(([name,value])=>`<div class="card"><small>${name}</small><h2>${esc(value)}</h2></div>`).join('')}</div><section class="table-card"><div class="table-head"><h2>게임별 운영 · 통계</h2><small>중지하면 신규 플레이가 차단됩니다. 진행 중인 게임은 완료할 수 있습니다.</small></div><div class="table-scroll"><table><thead><tr><th>게임</th><th>운영 상태</th><th>참여 회원</th><th>시작</th><th>클리어</th><th>완료율</th><th>평균 클리어 시간</th><th>관리</th></tr></thead><tbody>${data.items.map(g=>`<tr><td>${esc(g.title)}<br><small>${g.id}</small></td><td>${pill(g.enabled?'운영 중':'점검 중')}</td><td>${number(g.participants)}명</td><td>${number(g.started)}회</td><td>${number(g.completed)}회</td><td>${g.started?Math.round(100*g.completed/g.started):0}%</td><td>${g.completed?Math.round(g.durationMs/g.completed/1000)+'초':'—'}</td><td>${can('games')?`<button data-game-toggle="${g.id}" data-game-enable="${!g.enabled}">${g.enabled?'중지':'운영 재개'}</button>`:'조회 전용'}</td></tr>`).join('')}</tbody></table></div></section><section class="table-card" style="margin-top:24px"><div class="table-head"><h2>회원별 플레이 이력</h2><small>최신순 · 페이지당 25개</small></div>${plays.items.length?`<div class="table-scroll"><table><thead><tr><th>회원번호</th><th>게임</th><th>결과</th><th>시작</th><th>종료</th><th>시간</th></tr></thead><tbody>${plays.items.map(p=>`<tr><td><a href="#members/${encodeURIComponent(p.uid)}">${esc(p.uid)}</a></td><td>${esc(p.title)}</td><td>${esc(gameStatus[p.status])}</td><td>${fmt(p.createdAt)}</td><td>${fmt(p.finishedAt)}</td><td>${p.durationMs===null?'—':Math.round(p.durationMs/1000)+'초'}</td></tr>`).join('')}</tbody></table></div>`:empty('선택한 조건의 플레이 기록이 없습니다.')}<div class="pager"><span>이 페이지 ${plays.items.length}개</span><div class="row"><button data-action="first">처음</button><button data-cursor="${esc(plays.nextCursor||'')}" ${plays.nextCursor?'':'disabled'}>다음 →</button></div></div></section>`;
}
document.addEventListener('submit',e=>{if(e.target.id!=='gameFilterForm')return;e.preventDefault();const q=new URLSearchParams();for(const [k,v] of new FormData(e.target))if(v)q.set(k,v);goto('games?'+q);});
document.addEventListener('click',async e=>{
 const button=e.target.closest('[data-game-toggle]');if(!button)return;
 const enabled=button.dataset.gameEnable==='true';const reason=prompt((enabled?'운영 재개':'게임 중지')+' 사유를 입력해주세요.');if(!reason?.trim())return;
 button.disabled=true;try{await api('games/'+button.dataset.gameToggle,{method:'POST',body:{enabled,reason}});toast('게임 운영 설정을 저장했습니다.');await render();}catch(error){toast(error.message);button.disabled=false;}
});
